import { Customer, ContractDocument, ActivityNote, CalendarEvent, UserProfile, Organization } from "@/types/crm";

export const initialOrganizations: Organization[] = [
  {
    id: "stax",
    name: "StaxHQ",
    shortName: "Stax",
    address: "100 Innovation Way, Suite 400, Birmingham, AL 35203",
    phone: "(205) 555-0199",
    email: "operations@staxhq.com",
    website: "https://staxhq.com",
    taxId: "XX-XXXXXXX",
    defaultWatermark: "CONFIDENTIAL",
    isDemo: false,
    createdAt: Date.now() - 30 * 86400000,
  },
  {
    id: "demo-org",
    name: "StaxHQ Demo Sandbox",
    shortName: "Demo CRM",
    address: "777 Showcase Blvd, Demo City, CA 94105",
    phone: "(800) 555-DEMO",
    email: "demo@staxhq.com",
    website: "https://demo.staxhq.com",
    taxId: "DEMO-9999",
    defaultWatermark: "DEMO SAMPLE",
    isDemo: true,
    createdAt: Date.now() - 10 * 86400000,
  },
];

export const initialTeamMembers: UserProfile[] = [
  {
    uid: "user-1",
    displayName: "Admin Operator",
    email: "admin@staxhq.com",
    role: "admin",
    orgId: "stax",
    createdAt: Date.now() - 60 * 86400000,
  },
  {
    uid: "user-2",
    displayName: "Sarah Jenkins",
    email: "sarah@staxhq.com",
    role: "admin",
    orgId: "stax",
    createdAt: Date.now() - 45 * 86400000,
  },
  {
    uid: "user-3",
    displayName: "Marcus Vance",
    email: "marcus@staxhq.com",
    role: "employee",
    orgId: "stax",
    createdAt: Date.now() - 30 * 86400000,
  },
];

export const demoCustomers: Customer[] = [
  {
    id: "cust-1",
    orgId: "demo-org",
    name: "Town of Rehobeth",
    type: "customer",
    status: "active",
    industry: "Municipal Government",
    website: "https://rehobethal.gov",
    address: {
      street: "5449 County Road 203",
      city: "Rehobeth",
      state: "AL",
      zip: "36301",
    },
    contacts: [
      {
        id: "c-1",
        name: "Mayor John Abernathy",
        title: "Mayor / City Executive",
        email: "mayor@rehobethal.gov",
        phone: "(334) 555-0142",
        isPrimary: true,
      },
      {
        id: "c-2",
        name: "Eleanor Vance",
        title: "City Clerk & Treasurer",
        email: "evance@rehobethal.gov",
        phone: "(334) 555-0145",
        isPrimary: false,
      },
    ],
    financials: {
      totalContractValue: 48000,
      recurringAmount: 4000,
      billingCycle: "monthly",
      paymentStatus: "current",
      startDate: Date.now() - 180 * 86400000,
      nextRenewalDate: Date.now() + 185 * 86400000,
    },
    projects: [
      {
        id: "proj-1",
        name: "Municipal Work Order & Dispatch System",
        description: "Primary municipal work order dispatch, council meeting agendas, and citizen request routing.",
        status: "live",
        productsUsed: ["Core Dispatch Module", "Citizen Portal", "Billing Sync"],
        activeUsersCount: 14,
        leadEngineer: "Marcus Vance",
        updatedAt: Date.now() - 2 * 86400000,
      },
    ],
    tags: ["Municipal", "Government", "Annual Contract", "Key Account"],
    notesCount: 4,
    documentsCount: 3,
    createdAt: Date.now() - 180 * 86400000,
    updatedAt: Date.now() - 2 * 86400000,
  },
  {
    id: "cust-2",
    orgId: "demo-org",
    name: "Metro Public Utility Authority",
    type: "customer",
    status: "active",
    industry: "Utilities & Infrastructure",
    website: "https://metropublicutility.org",
    address: {
      street: "1200 Powerline Rd",
      city: "Birmingham",
      state: "AL",
      zip: "35205",
    },
    contacts: [
      {
        id: "c-3",
        name: "Robert Henderson",
        title: "VP Operations",
        email: "rhenderson@metroutility.org",
        phone: "(205) 555-9011",
        isPrimary: true,
      },
    ],
    financials: {
      totalContractValue: 120000,
      recurringAmount: 10000,
      billingCycle: "monthly",
      paymentStatus: "current",
      startDate: Date.now() - 90 * 86400000,
      nextRenewalDate: Date.now() + 275 * 86400000,
    },
    projects: [
      {
        id: "proj-2",
        name: "Smart Metering & Grid Incident Platform",
        status: "live",
        productsUsed: ["Incident Dispatch", "SMS Alert Engine"],
        activeUsersCount: 38,
        updatedAt: Date.now() - 5 * 86400000,
      },
    ],
    tags: ["Commercial", "Utility", "Enterprise"],
    notesCount: 2,
    documentsCount: 2,
    createdAt: Date.now() - 90 * 86400000,
    updatedAt: Date.now() - 5 * 86400000,
  },
  {
    id: "cust-3",
    orgId: "demo-org",
    name: "Tri-County Regional Medical Center",
    type: "prospect",
    status: "proposal_sent",
    industry: "Healthcare",
    website: "https://tricountymed.health",
    address: {
      street: "800 Health Parkway",
      city: "Montgomery",
      state: "AL",
      zip: "36104",
    },
    contacts: [
      {
        id: "c-4",
        name: "Dr. Amanda Wright",
        title: "Chief Information Officer",
        email: "awright@tricountymed.health",
        phone: "(334) 555-3882",
        isPrimary: true,
      },
    ],
    financials: {
      totalContractValue: 75000,
      recurringAmount: 6250,
      billingCycle: "monthly",
      paymentStatus: "pending",
      nextRenewalDate: Date.now() + 30 * 86400000,
    },
    projects: [],
    tags: ["Healthcare", "High Priority Lead", "Q3 Target"],
    notesCount: 3,
    documentsCount: 1,
    createdAt: Date.now() - 14 * 86400000,
    updatedAt: Date.now() - 1 * 86400000,
  },
];

export const demoContracts: ContractDocument[] = [
  {
    id: "doc-1",
    orgId: "demo-org",
    customerId: "cust-1",
    customerName: "Town of Rehobeth",
    title: "Master Services Agreement (MSA) - 2026",
    type: "agreement",
    status: "signed",
    fileName: "Rehobeth_MSA_Signed_2026.pdf",
    fileSizeBytes: 245190,
    watermarkText: "SIGNED & EXECUTED",
    signatureRequired: true,
    signatureData: {
      signerName: "John Abernathy",
      signerEmail: "mayor@rehobethal.gov",
      signedAt: Date.now() - 175 * 86400000,
      ipAddress: "68.102.44.12",
      auditLogId: "AUD-REH-98421",
    },
    createdAt: Date.now() - 180 * 86400000,
    updatedAt: Date.now() - 175 * 86400000,
  },
  {
    id: "doc-2",
    orgId: "demo-org",
    customerId: "cust-1",
    customerName: "Town of Rehobeth",
    title: "Service Level Agreement (SLA) & Support Schedule",
    type: "sla",
    status: "signed",
    fileName: "Rehobeth_SLA_Schedule_A.pdf",
    fileSizeBytes: 184200,
    watermarkText: "SIGNED & EXECUTED",
    signatureRequired: true,
    signatureData: {
      signerName: "John Abernathy",
      signerEmail: "mayor@rehobethal.gov",
      signedAt: Date.now() - 174 * 86400000,
      ipAddress: "68.102.44.12",
      auditLogId: "AUD-REH-98422",
    },
    createdAt: Date.now() - 180 * 86400000,
    updatedAt: Date.now() - 174 * 86400000,
  },
  {
    id: "doc-3",
    orgId: "demo-org",
    customerId: "cust-3",
    customerName: "Tri-County Regional Medical Center",
    title: "Enterprise Deployment Proposal & Statement of Work",
    type: "proposal",
    status: "sent_for_signature",
    fileName: "TriCounty_SOW_Proposal_Draft.pdf",
    fileSizeBytes: 412000,
    watermarkText: "CONFIDENTIAL",
    signatureRequired: true,
    createdAt: Date.now() - 10 * 86400000,
    updatedAt: Date.now() - 2 * 86400000,
  },
];

export const demoNotes: ActivityNote[] = [
  {
    id: "note-1",
    orgId: "demo-org",
    customerId: "cust-1",
    customerName: "Town of Rehobeth",
    authorId: "user-1",
    authorName: "Admin Operator",
    content: "Met with @Sarah Jenkins and Mayor Abernathy. Council unanimously approved our Q3 software updates and annual maintenance retainer. All systems operating at 100% capacity.",
    taggedUserIds: ["user-2"],
    category: "meeting",
    attachments: [],
    createdAt: Date.now() - 3 * 86400000,
  },
  {
    id: "note-2",
    orgId: "demo-org",
    customerId: "cust-1",
    customerName: "Town of Rehobeth",
    authorId: "user-2",
    authorName: "Sarah Jenkins",
    content: "Uploaded the counter-signed Master Services Agreement. Verified financial billing is set to $4,000 monthly auto-invoice via direct ACH.",
    taggedUserIds: [],
    category: "contract",
    attachments: [{ name: "Rehobeth_MSA_Signed_2026.pdf", url: "#", sizeBytes: 245190 }],
    createdAt: Date.now() - 175 * 86400000,
  },
  {
    id: "note-3",
    orgId: "demo-org",
    customerId: "cust-3",
    customerName: "Tri-County Regional Medical Center",
    authorId: "user-1",
    authorName: "Admin Operator",
    content: "Sent formal proposal to Dr. Amanda Wright. Scheduled demo review call with their IT director @Marcus Vance for next Thursday.",
    taggedUserIds: ["user-3"],
    category: "call_log",
    attachments: [],
    createdAt: Date.now() - 4 * 86400000,
  },
];

export const demoCalendarEvents: CalendarEvent[] = [
  {
    id: "evt-1",
    orgId: "demo-org",
    title: "Town of Rehobeth - Council Review & Demo",
    description: "Quarterly review with Mayor Abernathy and council members on work order system stats.",
    customerId: "cust-1",
    customerName: "Town of Rehobeth",
    start: Date.now() + 24 * 3600000, // tomorrow
    end: Date.now() + 25 * 3600000,
    attendeeUserIds: ["user-1", "user-2"],
    type: "meeting",
    syncStatus: "synced",
    createdAt: Date.now() - 2 * 86400000,
  },
  {
    id: "evt-2",
    orgId: "demo-org",
    title: "Tri-County Health - Technical Scope Review",
    description: "Deep dive with CIO Dr. Amanda Wright and network infrastructure leads.",
    customerId: "cust-3",
    customerName: "Tri-County Regional Medical Center",
    start: Date.now() + 72 * 3600000, // in 3 days
    end: Date.now() + 73.5 * 3600000,
    attendeeUserIds: ["user-1", "user-3"],
    type: "demo",
    syncStatus: "synced",
    createdAt: Date.now() - 1 * 86400000,
  },
  {
    id: "evt-3",
    orgId: "demo-org",
    title: "Metro Utility - Monthly Performance Sync",
    description: "Review smart metering uptime and dispatch ticket volume.",
    customerId: "cust-2",
    customerName: "Metro Public Utility Authority",
    start: Date.now() + 120 * 3600000, // in 5 days
    end: Date.now() + 121 * 3600000,
    attendeeUserIds: ["user-1"],
    type: "meeting",
    syncStatus: "synced",
    createdAt: Date.now() - 3 * 86400000,
  },
];
